runOnSave = true
key_path = "/usr/src/app/chefbc-cd4d1fb4ed74.json"
links = [
    "https://drive.google.com/file/d/1et0ir889jACxBcrjfTW_MkYOkGp2A5yM/view?usp=share_link",
    "https://drive.google.com/file/d/1psKIcHAWjugfdoyJUlf2vvc0LMqolhCD/view?usp=share_link",
    "https://drive.google.com/file/d/13Vq_BEq2e63fLzBhY2u1UV6TCdP967ay/view?usp=sharing",
]
calendar_url = "https://calendar.google.com/calendar/ical/73976030d4b82ca7595f9194853a0693015e1b7c3830133cacf67ac0f153e04b%40group.calendar.google.com/public/basic.ics"