version: '3.8'

services:

  streamlit:
    build: 
      dockerfile: ./Dockerfile
      context: ./
    # command: CMD streamlit run --server.port 8080 --server.enableCORS false app.py
    # volumes:
    #   - .:/app
    #   - .streamlit:/app/.streamlit
    volumes:
      # - ./data:/usr/src/app/data
      # - ./static:/usr/src/app/static
      - ./project:/usr/src/app
    ports:
      - 8080:8080
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    # env_file: 
    #   - .env
    # depends_on:
    #   - db
